replicaCount: 2
image:
  repository: ghcr.io/chabinhwang/my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30000

ingress:
  enabled: false
  hostname: myapp.example.com