replicaCount: 1
image:
  repository: ghcr.io/chabinhwang/my-app
  tag: 0bfae8d53a17b01328ca65e1b49eaae06e2ba3f9
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30000

ingress:
  enabled: false
  hostname: myapp.example.com

destination:
  server: https://kubernetes.default.svc
  namespace: test123