replicaCount: 1
image:
  repository: ghcr.io/chabinhwang/my-app
  tag: 51b54b1861e0450886fba72b8e8d6ea891f3c163
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30000

ingress:
  enabled: false
  hostname: myapp.example.com

destination:
  server: https://kubernetes.default.svc
  namespace: test123